Bookstore/Models/AUTHOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AUTHOR()
        {
            this.WROTEs = new HashSet<WROTE>();
        }
    
        public int AUTHOR_NUM { get; set; }
        public string AUTHOR_LAST { get; set; }
        public string AUTHOR_FIRST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WROTE> WROTEs { get; set; }
    }
}

Bookstore/Models/PUBLISHER.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookstore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLISHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLISHER()
        {
            this.BOOKs = new HashSet<BOOK>();
        }
    
        public string PUBLISHER_CODE { get; set; }
        public string PUBLISHER_NAME { get; set; }
        public string CITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK> BOOKs { get; set; }
    }
}

Bookstore/Controllers/SearchByBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Bookstore.Models;
using System.Web.Mvc;

namespace Bookstore.Controllers
{
    public class SearchByBookController : Controller
    {
        private BookstoreEntities db = new BookstoreEntities();
        // GET: SearchByBook
        public ActionResult Author()
        {
            SearchByBook model = new SearchByBook();

            model.AllBookOptions = db.AUTHORs.OrderBy(e => e.AUTHOR_LAST).ToList().Select(s => new SelectListItem
            {
                Text = s.AUTHOR_FIRST + " " + s.AUTHOR_LAST,
                Value = s.AUTHOR_NUM.ToString()
            });

            return PartialView("~/Views/Shared/_Author.cshtml", model);
        }

        public ActionResult Publisher()
        {
            SearchByBook model = new SearchByBook();

            model.AllBookOptions = db.PUBLISHERs.OrderBy(e => e.PUBLISHER_NAME).ToList().Select(s => new SelectListItem
            {
                Text = s.PUBLISHER_NAME,
                Value = s.PUBLISHER_CODE.ToString()
            });

            return PartialView("~/Views/Shared/_Publisher.cshtml", model);
        }


    }


}

Bookstore/Views/Shared/_Author.cshtml
@using Bookstore.Models;
@model SearchByBook

@using (Html.BeginForm("Author", "SearchByBook", FormMethod.Post))
{
    @Html.DropDownListFor(a => a.AuthorSelected, Model.AllBookOptions, "Select an Author", new { onchange = "document.location.href = '/Home/AuthorBrowse?id=' + this.options[this.selectedIndex].value;" });
}

Bookstore/Views/Shared/_BranchLocation.cshtml
@using Bookstore.Models;
@model SearchByBook

@using (Html.BeginForm("Branch", "SearchByBranch", FormMethod.Post))
{
    @Html.DropDownListFor(a => a.BranchLocation, Model.AllBranchLocations, "Please Choose a Location");
    @Html.ValidationMessageFor(d => d.BranchLocation, "", new { @class = "text-danger" })
}

Bookstore/Views/Shared/_BranchLocation2.cshtml
@using Bookstore.Models;
@model SearchByBook

@using (Html.BeginForm("Branch", "SearchByBranch", FormMethod.Post))
{
    @Html.DropDownListFor(a => a.BranchLocation, Model.AllBranchLocations, "Please Choose a Location", new { onchange = "document.location.href = '/Home/LocationBrowse?id=' + this.options[this.selectedIndex].value;" });
    @Html.ValidationMessageFor(d => d.BranchLocation, "", new { @class = "text-danger" })
}

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">
            <div class="bookHeader">
                <h1>Henry's Bookstore</h1>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <h2 class="internalBanner">For INTERNAL Use Only</h2>
        @RenderBody()
        <hr />
        <footer style="text-align:center">
            <p>
                This page is created for educational purposes only.<br />
                No images or content will be published to the internet for public use.<br />
                Book cover images were retrieved from Barnes and Nobel.
            </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bookstore/Views/Shared/_Nav.cshtml
@Html.ActionLink("Home", "Index", "Home")
<br />
@Html.ActionLink("Browse by Author", "AuthorBrowse", "Home")
<br />
@Html.ActionLink("Browse by Location", "LocationBrowse", "Home")
<br />
@Html.ActionLink("Browse by Publisher", "PublisherBrowse", "Home")
<br />
@Html.ActionLink("Browse Inventory", "InventoryBrowse", "Home")
<br />
@Html.ActionLink("Contact Management", "Contact", "Home")

Bookstore/Views/Shared/_Publisher.cshtml
@using Bookstore.Models;
@model SearchByBook

@using (Html.BeginForm("Publisher", "SearchByBook", FormMethod.Post))
{
    @Html.DropDownListFor(a => a.AuthorSelected, Model.AllBookOptions, "Select a Publisher", new { onchange = "document.location.href = '/Home/PublisherBrowse?id=' + this.options[this.selectedIndex].value;" });
}